### ISSUE TITLE
Fix test kitsune/wiki/tests/test_templates.py:NewRevisionTests.test_restore_draft_revision_with_older_based_on

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2963]
Test gets skipped.

```
Traceback (most recent call last):
  File "/app/kitsune/wiki/tests/test_templates.py", line 1100, in test_restore_draft_revision_with_older_based_on
    trans_content = pq(trans_resp.content)
  File "/usr/local/lib/python2.7/site-packages/pyquery/pyquery.py", line 226, in __init__
    elements = fromstring(context, self.parser)
  File "/usr/local/lib/python2.7/site-packages/pyquery/pyquery.py", line 70, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "/usr/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 726, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 614, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 629, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95015)
XMLSyntaxError: line 634: Tag footer invalid

```

See also #2931

**Comment by safwanrahman** [comment]
I have made another approach in #2904

**Comment by glogiotatidis** [comment]
> I have made another approach in #2904

This test is about restoring a revision, which should be unrelated to the session storage backend. Surely it breaks b/c of the change in the backend but we need to fix the test to work if the new backend.

**Comment by safwanrahman** [comment]
@glogiotatidis The test is related to the storage backend actually. Because in the test the cache needed to be deleted but as we are using cache for session storage, the session also got deleted and the client get logout.
Thats why it depends in sesion storage backend

**Comment by glogiotatidis** [comment]
I agree it breaks due to the cache backend change but it tests the restoration of a draft revision and the cache backend should be irrelevant

**Comment by akatsoulas** [comment]
This issue is too old and probably resolved by now. Please open a new issue if this is not the case.
