### ISSUE TITLE
celery workers generating too many errors to sentry, filling logs with tracebacks from http 429 responses

### ISSUE THREAD

**Issue by jgmize** [mozilla/kitsune#3262]
```
Traceback (most recent call last):
  File "/venv/lib/python2.7/site-packages/raven/transport/threaded.py", line 110, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/venv/lib/python2.7/site-packages/raven/transport/http.py", line 40, in send
    response = urlopen(req, data, self.timeout).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/venv/lib/python2.7/site-packages/newrelic/hooks/external_urllib2.py", line 16, in _nr_wrapper_opener_director_open_
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 429: Too Many Requests
http_sumo_app: 2018-07-03 17:07:38,567 sentry.errors:ERROR Failed to submit message: u'Error in timer: StopIteration()': /venv/lib/python2.7/site-packages/raven/base.py:527
```

**Comment by jgmize** [comment]
when enough of the workers get stuck in this state then no more celery tasks are processed and the "SUMO Enqueue Lag Monitor Task" dead man snitch alert is triggered. To restart the workers I used the following in each k8s cluster:

kubectl -n sumo-prod get pods | awk '/celery/ {print $1}' | xargs kubectl -n sumo-prod delete pod

**Comment by jgmize** [comment]
There are thousands of errors matching this issue: https://sentry.prod.mozaws.net/operations/sumo-aws-prod/issues/3394808/

StopIteration: null
  File "kombu/async/hub.py", line 140, in fire_timers
    entry()
  File "kombu/async/timer.py", line 64, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "kombu/async/timer.py", line 132, in _reschedules
    return fun(*args, **kwargs)
  File "billiard/pool.py", line 1246, in maintain_pool
    self._maintain_pool()
  File "billiard/pool.py", line 1238, in _maintain_pool
    self._repopulate_pool(joined)
  File "billiard/pool.py", line 1223, in _repopulate_pool
    self._create_worker_process(self._avail_index())
  File "billiard/pool.py", line 1049, in _create_worker_process
    inq, outq, synq = self.get_process_queues()
  File "celery/concurrency/asynpool.py", line 973, in get_process_queues
    return next(q for q, owner in items(self._queues)

**Comment by akatsoulas** [comment]
This is no longer relevant
