### ISSUE TITLE
Setup Issue: Bower version error

### ISSUE THREAD

**Issue by omkar-dsd** [mozilla/kitsune#3380]
On executing the setup command:
```
sudo docker-compose -f docker-compose.yml -f docker/composefiles/dev.yml run web ./node_modules/.bin/bower install --allow-root
```
Gives the following error.

```
/app/node_modules/bower/node_modules/tar-fs/node_modules/chownr/chownr.js:2
const fs = require('fs')
^^^^^
bower error         Use of const in strict mode.
```

I tried updating Node version to the latest (10.12.0) and latest LTS (8.12.0). Error still persists.

### Complete Error:
```
Starting kitsune_mariadb_1 ... done
Starting kitsune_elasticsearch_1 ... done
Starting kitsune_redis_1         ... done
? May bower anonymously report usage statistics to improve the tool over time? Yes

/app/node_modules/bower/node_modules/tar-fs/node_modules/chownr/chownr.js:2
const fs = require('fs')
^^^^^
bower error         Use of const in strict mode.

Stack trace:
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/app/node_modules/bower/node_modules/tar-fs/index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Console trace:
Error
    at StandardRenderer.error (/app/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/app/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/app/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /app/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/app/node_modules/bower/node_modules/q/q.js:864:24)
    at /app/node_modules/bower/node_modules/q/q.js:890:30
    at Promise.when (/app/node_modules/bower/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/app/node_modules/bower/node_modules/q/q.js:808:41)
    at /app/node_modules/bower/node_modules/q/q.js:570:49
System info:
Bower version: 1.4.1
Node version: 0.10.48
OS: Linux 4.10.0-28-generic x64
```

**Comment by pmac** [comment]
We ran into that recently and fixed it I thought. Try running the `docker pull` steps again from earlier in the readme to get the latest images.

**Comment by omkar-dsd** [comment]
> Bower version: 1.4.1
> Node version: 0.10.48
> OS: Linux 4.10.0-28-generic x64

Are these compatible? I am still getting this issue.

**Comment by omkar-dsd** [comment]
>npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/ . #3381

**Comment by pmac** [comment]
We updated the bower version, but it was then failing to build the prod images due to an outdated `yarn.lock` file. It turns out the root cause of this was that the dev image was still installing Node 0.10 while prod had moved to Node 6.x and Yarn. I've filed #3386 to fix this and update the readme file to use yarn instead of npm.

**Comment by omkar-dsd** [comment]
@pmac Closing this. Taken on #3386 .
