### ISSUE TITLE
Docker Install Error: Failed Migration

### ISSUE THREAD

**Issue by bensternthal** [mozilla/kitsune#3467]
Running the docker install from scratch it completes but i see this error when looking at http://0.0.0.0:8000/en-US/:

```
OperationalError at /
(1054, "Unknown column 'products_product.image_alternate' in 'field list'")
```

Looking at the install log it looks to be a failing migration.

```
django.db.utils.OperationalError: (1050, "Table 'djcelery_crontabschedule' already exists")
make: *** [init] Error 1
```

Re-running the install or running manage migrate or syncdb using docker exec results in same error. Full trace is below:

```
Running migrations:
  Rendering model states... DONE
  Applying djcelery.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 32, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/venv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/venv/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1050, "Table 'djcelery_crontabschedule' already exists")
```

**Comment by pmac** [comment]
Interesting. I'm assuming  you've run this all before? The volume in the docker-compose.yml file means that the DB will be persistent, so it may well have gotten into a strange state. Would probably be better to start fresh unless there's a good reason to keep your existing local db. 

If you'd like to start fresh you should be able to run the following command:

```shell
 $ docker volume rm kitsune_mysqlvolume
```

**Comment by bensternthal** [comment]
I tried that yesterday. Stopping all containers, rm-ing and starting again. Same error.  Tried again this morning _just in case_ and same error.

**Comment by pmac** [comment]
I just tried this, and it failed to remove that volume until I removed the containers. Here's what I did to get the site running from scratch:

```bash
$ docker-compose stop
$ docker-compose rm
$ docker volume rm kitsune_mysqlvolume
$ make init
$ make run
```

That resulted in a functional (but empty) site. LMK how that goes.

**Comment by bensternthal** [comment]
ah ok this worked.

I was deleting the containers and not the volume. And when I read your comment.. i totally missed you were deleting the volume and just repeated the same mistake. 

![qhcmv0z](https://user-images.githubusercontent.com/198507/53110607-293a6900-34f0-11e9-882d-882fc54ca779.jpg)
