### ISSUE TITLE
Batch request error: Read timed out

### ISSUE THREAD

**Issue by finn0** [mozilla/kitsune#4511]
### Description
For batch process like in [Dockerfiles#L38](https://github.com/mozilla/kitsune/blob/master/Dockerfile#L38); users may get a pip's timeout error message, if they have low bandwidth.

### Steps to reproduce
- Follow development setup instruction, till `make init` command in 2nd step.
- Run `make build` command

### Actual output
Getting time out error

### Additional

Output log (some portion of output has been redacted):
```bash
Step 18/23 : RUN pip install --no-cache-dir --require-hashes -r requirements/default.txt &&     pip install --no-cache-dir --require-hashes -r requirements/dev.txt &&     pip install --no-cache-dir --require-hashes -r requirements/test.txt
 ---> Running in 8ec216ddd926
Collecting amqp==2.6.0
  Downloading amqp-2.6.0-py2.py3-none-any.whl (47 kB)
Collecting apscheduler==3.6.3
  Downloading APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)
Collecting babel==2.8.0
  Downloading Babel-2.8.0-py2.py3-none-any.whl (8.6 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 332, in run
    requirement_set = resolver.resolve(
  File "/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
    local_file = unpack_url(
  File "/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 255, in unpack_url
    file = get_http_url(
  File "/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 129, in get_http_url
    from_path, content_type = _download_http_url(
  File "/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 281, in _download_http_url
    for chunk in download.chunks:
  File "/venv/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 166, in iter
    for x in it:
  File "/venv/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 15, in response_chunks
    for chunk in response.raw.stream(
  File "/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/venv/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'base-dev' failed to build: The command '/bin/sh -c pip install --no-cache-dir --require-hashes -r requirements/default.txt &&     pip install --no-cache-dir --require-hashes -r requirements/dev.txt &&     pip install --no-cache-dir --require-hashes -r requirements/test.txt' returned a non-zero code: 2
make: *** [Makefile:46: build] Error 1
```

**Comment by finn0** [comment]
Default Pip's socket timeout value is 60s, which is very less for batch processes like mention in [Dockerfiles#L38](https://github.com/mozilla/kitsune/blob/master/Dockerfile#L38). So setting it to something bigger would be good idea.
